#![recursion_limit = "256"]

[package]
name = "vgtk-todomvc"
version = "0.1.0"
authors = ["Ville <ville.heikkinen@wunderdog.fi>"]
edition = "2018"

[dependencies]
vgtk = "0.2"
pretty_env_logger = "0.4"
